// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6WbMuXYpycjPKZn08BmozrJsvdHV75o8',
    appId: '1:156337252426:web:25e9869a27d1a6b506deb3',
    messagingSenderId: '156337252426',
    projectId: 'findyourphone-aa9e9',
    authDomain: 'findyourphone-aa9e9.firebaseapp.com',
    storageBucket: 'findyourphone-aa9e9.firebasestorage.app',
    measurementId: 'G-HVCSXQNQPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZjMfBpvjfa485wYNc3xJ91vMHlm9E5Gk',
    appId: '1:156337252426:android:a2a7e65f99d9a51d06deb3',
    messagingSenderId: '156337252426',
    projectId: 'findyourphone-aa9e9',
    storageBucket: 'findyourphone-aa9e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJUoRCaREYPfeUkQzQprwaiXn67qptDI',
    appId: '1:156337252426:ios:f8798927c461c19e06deb3',
    messagingSenderId: '156337252426',
    projectId: 'findyourphone-aa9e9',
    storageBucket: 'findyourphone-aa9e9.firebasestorage.app',
    iosBundleId: 'com.kms.findyourphone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJUoRCaREYPfeUkQzQprwaiXn67qptDI',
    appId: '1:156337252426:ios:f8798927c461c19e06deb3',
    messagingSenderId: '156337252426',
    projectId: 'findyourphone-aa9e9',
    storageBucket: 'findyourphone-aa9e9.firebasestorage.app',
    iosBundleId: 'com.kms.findyourphone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6WbMuXYpycjPKZn08BmozrJsvdHV75o8',
    appId: '1:156337252426:web:423ae4028e5c0a8806deb3',
    messagingSenderId: '156337252426',
    projectId: 'findyourphone-aa9e9',
    authDomain: 'findyourphone-aa9e9.firebaseapp.com',
    storageBucket: 'findyourphone-aa9e9.firebasestorage.app',
    measurementId: 'G-E06LPFW2MY',
  );
}
